
services:
  web:
    build: .
    ports:
      - "18080:8080"
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env
    environment:
      - GIN_MODE=release
    restart: unless-stopped